Parameters:
  MyParamater:
    Description: Parameter Description
    Type: String  


Resources:
  MyInstance:
    Type: AWS::EC2::Instance
    Properties:
      AvailabilityZone: us-east-1a
      ImageId: ami-a4c7edb2
      InstanceType: t2.micro

MyEIP:
  Type: AWS::EC2::EIP
  Properties: 
    InstanceId: !Ref MyInstance

SSHSecurityGroup:
  Type: AWS::EC2::SecurityGroup 
  GroupDescription: !Ref MyParamater
  SecurityGroupIngress:
  - IpProtocol: tcp
    FromPort: 80
  - IpProtocol: tcp
    FromPort: 22